name: ShellCheck

on:
  push:
    paths:
      - 'scripts/**/*.sh'
  pull_request:
    paths:
      - 'scripts/**/*.sh'

jobs:
  shellcheck:
    name: Lint shell scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts'
          severity: warning
